services:
  app:
    container_name: tm-be
    build: .
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
